### ISSUE TITLE
Block Render Error when trying to render mermaid diagram

### ISSUE THREAD

**Issue by priisholm** [xyhp915/logseq-fenced-code-plus#42]
Hi,

After installing the plugin, I tried to render a simple diagram:

```mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
```

However, in logseq, it is shown as such:

![image](https://github.com/xyhp915/logseq-fenced-code-plus/assets/574245/9423a87e-a347-4986-a509-56856e456fd7)

Error copied from the console:

```
TypeError: c.mermaid.init is not a function
    at mermaid.tsx:47:20
    at Tj (react-dom.production.min.js:179:399)
    at unstable_runWithPriority (react.production.min.js:24:26)
    at Za (react-dom.production.min.js:73:8)
    at Ra (react-dom.production.min.js:178:368)
    at gf (react-dom.production.min.js:161:497)
    at react-dom.production.min.js:73:230
    at unstable_runWithPriority (react.production.min.js:24:26)
    at Za (react-dom.production.min.js:73:8)
    at $g (react-dom.production.min.js:73:176)
```

Fenced code plus version: **0.0.7**

LogSeq version: **0.10.5** (c4341c1)

Best,
Kenneth

**Comment by xyhp915** [comment]
Hi @priisholm Could you try the latest version (0.0.9) for this issue?

**Comment by taweili** [comment]
> Hi @priisholm Could you try the latest version (0.0.9) for this issue?

![image](https://github.com/xyhp915/logseq-fenced-code-plus/assets/6722/99cecbc6-6201-4e49-ad90-227bbf86d8c2)


I also get the same error with 0.0.9 of the plugin and 0.10.6 of logseq. 

![image](https://github.com/xyhp915/logseq-fenced-code-plus/assets/6722/836e279e-a578-4f57-9509-3955f673035f)
![image](https://github.com/xyhp915/logseq-fenced-code-plus/assets/6722/94d09617-56f2-45a6-bbf5-f2b85622fcba)
